### ISSUE TITLE
Rename starter API (HookRoot)

### ISSUE THREAD

**Issue by xiel** [xiel/outer-hooks#28]
- start API is named weirdly atm. 
`const myHook = HookRoot(useMyHook)`
- should be a verb probably
  - ideas: startHook, runHook, launchHook, hookyHookface

**Comment by davidcetinkaya** [comment]
hookyHookface 🤣

**Comment by xiel** [comment]
Released in https://github.com/xiel/outer-hooks/releases/tag/v0.0.4-beta
